name: Update Profile README (uptime + repos)

on:
  schedule:
    - cron: "0 * * * *"   # alle 1 Stunde
  workflow_dispatch:

permissions:
  contents: write   # nötig für git push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sanity check paths (debug)
        run: |
          pwd
          ls -lah
          ls -lah profile || true

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Update uptime block
        env:
          FILE: profile/README.md
          GH_USER: mzcydev
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Marker müssen im FILE vorhanden sein
          test -f "$FILE" || { echo "::error file=$FILE::File not found"; exit 1; }

          START_DATE="2017-01-01"

          # Anzahl Commits über die Search API holen (alle Commits vom User seit START_DATE)
          COMMITS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/search/commits?q=author:${GH_USER}+author-date:>=${START_DATE}" \
            -H "Accept: application/vnd.github.cloak-preview" \
            | jq -r '.total_count')

          # Fallback, falls API nichts liefert
          [ -z "$COMMITS" ] && COMMITS="0"

          LOAD="0.42, 0.33, 0.12"
          NOW=$(date -u +"%s")
          START=$(date -u -d "$START_DATE" +"%s") || START=0
          DAYS=$(( (NOW - START) / 86400 ))

          LINE=" $(date +%H:%M:%S) up ${DAYS} days,  ${COMMITS} commits,  load average: ${LOAD}"

          sed -i "/<!-- UPTIME-START -->/,/<!-- UPTIME-END -->/c\<!-- UPTIME-START -->\n\`\`\`bash\nroot@${GH_USER}:~# uptime\n$LINE\n\`\`\`\n<!-- UPTIME-END -->" "$FILE"


      - name: Update repos block
        env:
          FILE: profile/README.md
          GH_USER: mzcydev
        run: |
          # Marker: <!-- REPOS-START --> ... <!-- REPOS-END -->
          test -f "$FILE" || { echo "::error file=$FILE::File not found"; exit 1; }

          JSON=$(curl -s "https://api.github.com/users/${GH_USER}/repos?per_page=100&sort=pushed")
          NAMES=$(echo "$JSON" | jq -r '.[].name' | head -n 5)

          DATE=$(date +"%b %d")
          OUTPUT=""
          while IFS= read -r R; do
            [ -z "$R" ] && continue
            OUTPUT="${OUTPUT}\ndrwxr-xr-x  2 ${GH_USER} dev 4.0K ${DATE}  ${R}"
          done <<< "$NAMES"

          [ -z "$OUTPUT" ] && OUTPUT="\ndrwxr-xr-x  2 ${GH_USER} dev 4.0K ${DATE}  README.md"

          sed -i "/<!-- REPOS-START -->/,/<!-- REPOS-END -->/c\<!-- REPOS-START -->\n\`\`\`bash\nroot@${GH_USER}:~# ls -lah ~/repos/\n$OUTPUT\n\`\`\`\n<!-- REPOS-END -->" "$FILE"

      - name: Commit & push
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/README.md
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "chore: auto-update uptime & repos"
          git push
