name: Update README uptime

on:
  schedule:
    - cron: "0 * * * *"   # jede Stunde
  workflow_dispatch:      # manuelles Triggern möglich

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate uptime
        run: |
          START_DATE="2017-01-01 00:00:00"
          NOW=$(date -u +"%s")
          START=$(date -u -d "$START_DATE" +"%s")
          DAYS=$(( (NOW - START) / 86400 ))
          LINE=" $(date +%H:%M:%S) up ${DAYS} days,  214 commits,  load average: 0.42, 0.33, 0.12"
      
          # ganzen Block zwischen den Markern ersetzen (Marker bleiben unsichtbar, weil außerhalb des Codeblocks)
          sed -i "/<!-- UPTIME-START -->/,/<!-- UPTIME-END -->/c\<!-- UPTIME-START -->\n\`\`\`bash\nroot@mzcydev:~# uptime\n$LINE\n\`\`\`\n<!-- UPTIME-END -->" README.md
      - name: Update repos in README
        run: |
          # Hole die 5 meist-gepushten Repos von deinem Account via GitHub API
          REPOS=$(curl -s "https://api.github.com/users/mzcydev/repos?per_page=5&sort=pushed" \
            | jq -r '.[].name' | head -n 5)
      
          DATE=$(date +"%b %d")
          OUTPUT=""
          for R in $REPOS; do
            OUTPUT="$OUTPUT\ndrwxr-xr-x  2 mzcydev dev 4.0K $DATE  $R"
          done
      
          # Block im README ersetzen
          sed -i "/<!-- REPOS-START -->/,/<!-- REPOS-END -->/c\<!-- REPOS-START -->\n\`\`\`bash\nroot@mzcydev:~# ls -lah ~/repos/\n$OUTPUT\n\`\`\`\n<!-- REPOS-END -->" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Update uptime" || echo "No changes to commit"
          git push || true

