name: Update README uptime

on:
  schedule:
    - cron: "0 * * * *"   # jede Stunde
  workflow_dispatch:      # manuelles Triggern möglich

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate uptime
        run: |
          START_DATE="2017-01-01 00:00:00"
          NOW=$(date -u +"%s")
          START=$(date -u -d "$START_DATE" +"%s")
          DAYS=$(( (NOW - START) / 86400 ))
          LINE=" $(date +%H:%M:%S) up ${DAYS} days,  214 commits,  load average: 0.42, 0.33, 0.12"
      
          # ganzen Block zwischen den Markern ersetzen (Marker bleiben unsichtbar, weil außerhalb des Codeblocks)
          sed -i "/<!-- UPTIME-START -->/,/<!-- UPTIME-END -->/c\<!-- UPTIME-START -->\n\`\`\`bash\nroot@mzcydev:~# uptime\n$LINE\n\`\`\`\n<!-- UPTIME-END -->" README.md

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "Update uptime"
          git push
